#!/usr/bin/env python3
"""Clean temporary artifacts generated by Grimoire rites.

Removes .artifacts/ directories under rites/ in Arcana and all
installed grimoires. These contain validation logs, canonical
terminology extracts, and parallel run results.

Usage:
    python3 rites/clean_artifacts.py             # clean all
    python3 rites/clean_artifacts.py --dry-run    # preview only
"""

import argparse
import shutil
import sys
from pathlib import Path

from _lib import load_library, resolve_local_path

ARCANA_PATH = Path(__file__).resolve().parent.parent
GRIMOIRES_HOME = Path.home() / "grimoires"
LOCAL_LIBRARY = GRIMOIRES_HOME / "library.json"

ARTIFACTS_DIR_NAME = ".artifacts"


def clean_location(base_path, label, dry_run=False):
    """Remove .artifacts/ under base_path/rites/. Returns file count removed."""
    arts = base_path / "rites" / ARTIFACTS_DIR_NAME
    if not arts.is_dir():
        return 0

    count = sum(1 for f in arts.rglob("*") if f.is_file())
    if dry_run:
        print(f"  [DRY]   Would remove {arts} ({count} file(s))")
    else:
        shutil.rmtree(arts)
        print(f"  [OK]    Cleaned {arts} ({count} file(s))")
    return count


def main():
    parser = argparse.ArgumentParser(description="Clean Grimoire rite artifacts")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be removed without deleting")
    args = parser.parse_args()

    print()
    print("  Grimoire Artifact Cleanup")
    print("  ----------------------------")
    print()

    if args.dry_run:
        print("  [INFO]  Dry run mode - no files will be deleted")
        print()

    total = 0

    total += clean_location(ARCANA_PATH, "Arcana", args.dry_run)

    if LOCAL_LIBRARY.is_file():
        library = load_library(LOCAL_LIBRARY)
        for key in sorted(library["grimoires"].keys()):
            entry = library["grimoires"][key]
            local_path = resolve_local_path(entry.get("local_path", ""))
            if local_path.is_dir():
                total += clean_location(local_path, key, args.dry_run)
    else:
        print("  [INFO]  No local library - only Arcana cleaned")

    print()
    print("  ----------------------------")
    if total == 0:
        print("  Nothing to clean.")
    elif args.dry_run:
        print(f"  Would remove {total} file(s).")
    else:
        print(f"  Removed {total} file(s).")
    print()


if __name__ == "__main__":
    sys.exit(main())
