#!/usr/bin/env python3
"""Grimoire Skill Registration — cross-platform skill installer.

Discovers skills from Arcana and all installed grimoires,
cleans stale skills by namespace prefix, templates path placeholders,
and installs to ~/.claude/skills/.

Each source gets a namespace prefix derived from its catalog key:
    Arcana:           grm-
    olympus-grimoire: olympus-
    bd-grimoire:      bd-

Usage:
    python3 register_skills.py [--dry-run]
"""

import argparse
import json
import os
import shutil
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ARCANA_PATH = Path(__file__).resolve().parent.parent
GRIMOIRE_HOME = Path.home() / "grimoire"
LOCAL_CATALOG = GRIMOIRE_HOME / "catalog.json"
SKILLS_TARGET = Path.home() / ".claude" / "skills"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------


def info(msg):
    print(f"  [INFO]  {msg}")


def ok(msg):
    print(f"  [OK]    {msg}")


def warn(msg):
    print(f"  [WARN]  {msg}")


def err(msg):
    print(f"  [ERROR] {msg}")


# ---------------------------------------------------------------------------
# Core operations
# ---------------------------------------------------------------------------


def clean_prefix(prefix, dry_run=False):
    """Remove all skill directories matching a namespace prefix."""
    cleaned = 0
    if not SKILLS_TARGET.is_dir():
        return cleaned

    for skill_dir in sorted(SKILLS_TARGET.iterdir()):
        if skill_dir.is_dir() and skill_dir.name.startswith(prefix):
            if dry_run:
                info(f"Would remove: {skill_dir.name}")
            else:
                shutil.rmtree(skill_dir)
            cleaned += 1
    return cleaned


def register_skill(source_dir, registered_name, arcana_path, grimoire_path="",
                    source_label="Arcana", dry_run=False):
    """Template and install a single skill. Returns True if registered."""
    source_file = source_dir / "SKILL.md"

    if not source_file.is_file():
        warn(f"No SKILL.md found in {source_dir} (skipping)")
        return False

    if dry_run:
        info(f"Would register: /{registered_name} ({source_label})")
        return True

    target_dir = SKILLS_TARGET / registered_name
    target_dir.mkdir(parents=True, exist_ok=True)

    # Template all files in the skill directory
    for source in source_dir.iterdir():
        if not source.is_file():
            continue
        content = source.read_text(encoding="utf-8")
        content = content.replace("{{ARCANA_PATH}}", str(arcana_path))
        if grimoire_path:
            content = content.replace("{{GRIMOIRE_PATH}}", str(grimoire_path))

        # Add provenance header to SKILL.md so AI knows this is a generated copy
        if source.name == "SKILL.md":
            provenance = (
                f"\n<!-- GENERATED — source: {source_dir}/SKILL.md | "
                f"DO NOT EDIT this file. Edit the source and run /grm-register-skills. -->\n"
            )
            # Insert after frontmatter closing ---
            parts = content.split("---", 2)
            if len(parts) >= 3:
                content = parts[0] + "---" + parts[1] + "---" + provenance + parts[2]

        (target_dir / source.name).write_text(content, encoding="utf-8")

    ok(f"Registered: /{registered_name} ({source_label})")
    return True


def register_arcana_skills(dry_run=False):
    """Register all Arcana skills (grm-* prefix)."""
    skills_dir = ARCANA_PATH / "skills"
    prefix = "grm-"

    if not skills_dir.is_dir():
        warn(f"No skills directory in Arcana at {skills_dir}")
        return 0, 0

    info(f"Cleaning {prefix}* namespace...")
    cleaned = clean_prefix(prefix, dry_run)

    info("Scanning Arcana skills...")
    registered = 0

    for skill_dir in sorted(skills_dir.iterdir()):
        if not skill_dir.is_dir():
            continue
        name = f"{prefix}{skill_dir.name}"
        if register_skill(skill_dir, name, ARCANA_PATH, dry_run=dry_run):
            registered += 1

    return registered, cleaned


def register_grimoire_skills(dry_run=False):
    """Register skills from all installed domain grimoires."""
    if not LOCAL_CATALOG.is_file():
        info(f"No local catalog at {LOCAL_CATALOG} — skipping domain skills")
        return 0, 0

    try:
        with open(LOCAL_CATALOG) as f:
            catalog = json.load(f)
    except (json.JSONDecodeError, OSError):
        warn("Could not read local catalog — skipping domain skills")
        return 0, 0

    total_registered = 0
    total_cleaned = 0

    for key in sorted(catalog.get("grimoires", {}).keys()):
        entry = catalog["grimoires"][key]
        raw_path = entry.get("local_path", "")

        # Expand $HOME
        local_path = Path(raw_path.replace("$HOME", str(Path.home())))

        if not local_path.is_dir():
            info(f"{key}: directory not found at {local_path} (skipping)")
            continue

        skills_dir = local_path / "skills"
        if not skills_dir.is_dir():
            info(f"{key}: no skills/ directory (skipping)")
            continue

        # Derive namespace prefix: "olympus-grimoire" → "olympus-"
        if key.endswith("-grimoire"):
            prefix = key[: -len("-grimoire")] + "-"
        else:
            prefix = key + "-"

        info(f"Cleaning {prefix}* namespace...")
        cleaned = clean_prefix(prefix, dry_run)
        total_cleaned += cleaned

        info(f"Scanning {key} skills...")

        for skill_dir in sorted(skills_dir.iterdir()):
            if not skill_dir.is_dir():
                continue
            name = f"{prefix}{skill_dir.name}"
            if register_skill(
                skill_dir, name, ARCANA_PATH, str(local_path), key, dry_run
            ):
                total_registered += 1

    return total_registered, total_cleaned


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="Grimoire Skill Registration")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done without making changes")
    args = parser.parse_args()

    print()
    print("  Grimoire Skill Registration")
    print("  ----------------------------")
    print()

    if args.dry_run:
        info("Dry run mode — no files will be written")
        print()

    SKILLS_TARGET.mkdir(parents=True, exist_ok=True)

    arcana_registered, arcana_cleaned = register_arcana_skills(args.dry_run)
    grimoire_registered, grimoire_cleaned = register_grimoire_skills(args.dry_run)

    total_registered = arcana_registered + grimoire_registered
    total_cleaned = arcana_cleaned + grimoire_cleaned

    print()
    print("  ----------------------------")
    print(f"  Registered: {total_registered} skill(s)")
    if total_cleaned > 0:
        print(f"  Cleaned:    {total_cleaned} stale skill(s)")
    print()

    if not args.dry_run and total_registered > 0:
        print("  Skills are now available in any Claude Code session.")
        print("  Try: /grm-help")
        print()


if __name__ == "__main__":
    main()
