#!/usr/bin/env python3
"""Grimoire Skill Registration - cross-platform skill installer.

Discovers skills from Arcana and, by default, all installed grimoires. It can
also target one grimoire with --grimoire. The rite renders pointer skills into
supported agent skill directories, stamps each generated SKILL.md with Arcana
ownership metadata, and removes stale generated skills only when ownership can
be proven from that metadata.

Mutation profile: plan_apply. `--dry-run` prints the planned creates, updates,
owned cleanups, preserved unowned directories, and collisions without writing.
The default mode applies the same plan to the selected agent skill targets.

Usage:
    python3 sync_skills.py [--agent all|TARGET] [--grimoire PATH] [--dry-run] [--reset-managed]

Exit codes: 0 = plan completed or apply completed, 1 = apply blocked by
collision, 2 = argparse invalid arguments.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from diagnostics import ResultReporter, add_output_format_arg
from agent_targets import skill_registration_targets
from _lib import (
    SKILL_PREFIX_PLACEHOLDER,
    SKILL_PREFIX_RE,
    SKILL_SLUG_RE,
    info,
    load_library,
    load_manifest,
    ok,
    read_frontmatter_name,
    resolve_local_path,
    warn,
)


ARCANA_PATH = Path(__file__).resolve().parent.parent
ARCANA_MANIFEST = ARCANA_PATH / "arcana.json"
GRIMOIRES_HOME = Path.home() / "grimoires"
LOCAL_LIBRARY = GRIMOIRES_HOME / "library.json"

OWNERSHIP_MARKER = "ARCANA_SKILL_OWNERSHIP"
OWNERSHIP_SCHEMA_VERSION = 1
REGISTER_GENERATION = 1
OWNERSHIP_MARKER_RE = re.compile(r"<!--\s*ARCANA_SKILL_OWNERSHIP\s+")
GENERATED_SOURCE_RE = re.compile(
    # Match a hyphen, en-dash, or em-dash separator so every generated skill
    # stays provably Arcana-owned and can be cleaned up or re-owned mechanically.
    r"<!--\s*GENERATED\s*[-–—]\s*source:\s*(.*?)\s*\|\s*DO NOT EDIT this file\.",
    re.DOTALL,
)

SKILL_TARGETS = skill_registration_targets(ARCANA_PATH)


@dataclass(frozen=True)
class SkillSpec:
    """One renderable source skill."""

    command_name: str
    command_slug: str
    skill_prefix: str
    source_dir: Path
    source_label: str
    source_kind: str
    source_key: str
    source_repo: str
    grimoire_path: str = ""


@dataclass(frozen=True)
class PlanAction:
    """One planned registration action."""

    action: str
    command_name: str
    target_dir: Path
    spec: SkillSpec | None = None
    reason: str = ""
    owner: dict[str, Any] | None = None


def is_valid_skill_prefix(skill_prefix: str) -> bool:
    """Return True when skill_prefix is a compact lowercase slug like grm."""
    return bool(SKILL_PREFIX_RE.fullmatch(skill_prefix))


def is_valid_skill_slug(slug: str) -> bool:
    """Return True when a skill slug uses lowercase hyphenated command syntax."""
    return bool(SKILL_SLUG_RE.fullmatch(slug))


def load_grimoire_metadata(grimoire_root: Path, label: str) -> tuple[dict[str, Any] | None, str | None]:
    """Load and skill_prefix-validate a grimoire manifest."""
    metadata, errors = load_manifest(grimoire_root)
    if metadata is None:
        warn(f"{label}: {errors[0]} (skipping)")
        return None, None
    if errors:
        warn(f"{label}: {errors[0]} (skipping)")
        return None, None
    return metadata, metadata.get("skill_prefix", "")


def load_arcana_metadata() -> tuple[dict[str, Any] | None, str | None]:
    """Load and validate Arcana's own manifest."""
    try:
        metadata = json.loads(ARCANA_MANIFEST.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        warn(f"Arcana: could not read arcana.json: {exc} (skipping)")
        return None, None

    skill_prefix = metadata.get("skill_prefix", "")
    if metadata.get("kind") != "arcana":
        warn("Arcana: arcana.json missing kind='arcana' (skipping)")
        return None, None
    if not skill_prefix or not SKILL_PREFIX_RE.fullmatch(skill_prefix):
        warn(
            "Arcana: arcana.json missing valid 'skill_prefix' "
            f"(must match {SKILL_PREFIX_RE.pattern})"
        )
        return None, None
    return metadata, skill_prefix


def load_arcana_skill_families() -> list[dict[str, Any]]:
    """Return normalized Arcana command-family definitions from arcana.json."""
    metadata, default_prefix = load_arcana_metadata()
    if metadata is None:
        return []

    raw_families = metadata.get("skill_families")
    if not isinstance(raw_families, dict) or not raw_families:
        raw_families = {
            "arcana": {
                "skill_prefix": default_prefix,
                "path": "skills",
                "slug_prefix": "",
            }
        }

    families: list[dict[str, Any]] = []
    seen_names: set[str] = set()
    for name, config in raw_families.items():
        if not isinstance(config, dict):
            warn(f"Arcana: skill_families.{name} must be an object (skipping)")
            continue
        skill_prefix = config.get("skill_prefix", default_prefix)
        rel_path = config.get("path", "")
        slug_prefix = config.get("slug_prefix", "")

        if name in seen_names:
            warn(f"Arcana: duplicate skill family '{name}' (skipping)")
            continue
        seen_names.add(name)
        if not skill_prefix or not SKILL_PREFIX_RE.fullmatch(skill_prefix):
            warn(f"Arcana: skill family '{name}' has invalid skill_prefix (skipping)")
            continue
        if not rel_path or Path(rel_path).is_absolute():
            warn(f"Arcana: skill family '{name}' has invalid relative path (skipping)")
            continue
        if slug_prefix and not SKILL_SLUG_RE.fullmatch(slug_prefix):
            warn(f"Arcana: skill family '{name}' has invalid slug_prefix (skipping)")
            continue

        families.append({
            "name": name,
            "skill_prefix": skill_prefix,
            "path": ARCANA_PATH / rel_path,
            "slug_prefix": slug_prefix,
        })

    return families


def resolve_grimoire_path(raw_path: str | Path) -> Path:
    """Resolve a user/library grimoire path, including $HOME placeholders."""
    return resolve_local_path(str(raw_path), resolve=True)


def build_skill_spec(
    skill_dir: Path,
    skill_prefix: str,
    command_slug: str,
    source_label: str,
    source_kind: str,
    source_key: str,
    source_repo: str,
    grimoire_path: str = "",
) -> SkillSpec | None:
    """Validate a source skill folder and return a renderable spec."""
    source_file = skill_dir / "SKILL.md"
    if not source_file.is_file():
        warn(f"No SKILL.md found in {skill_dir} (skipping)")
        return None

    expected_template = f"{SKILL_PREFIX_PLACEHOLDER}-{command_slug}"
    declared_name_template = read_frontmatter_name(source_file)
    if declared_name_template != expected_template:
        warn(
            f"{skill_dir}: SKILL.md name must be '{expected_template}' "
            f"(found '{declared_name_template or '<missing>'}')"
        )
        return None

    return SkillSpec(
        command_name=f"{skill_prefix}-{command_slug}",
        command_slug=command_slug,
        skill_prefix=skill_prefix,
        source_dir=skill_dir,
        source_label=source_label,
        source_kind=source_kind,
        source_key=source_key,
        source_repo=source_repo,
        grimoire_path=grimoire_path,
    )


def collect_arcana_skill_specs() -> list[SkillSpec]:
    """Collect Arcana-shipped skills from command families."""
    specs: list[SkillSpec] = []
    for family in load_arcana_skill_families():
        skills_dir = family["path"]
        if not skills_dir.is_dir():
            warn(f"Arcana: no skills directory for family '{family['name']}' at {skills_dir}")
            continue
        for skill_dir in sorted(skills_dir.iterdir()):
            if not skill_dir.is_dir():
                continue
            if not is_valid_skill_slug(skill_dir.name):
                warn(f"{skill_dir}: invalid skill directory slug (skipping)")
                continue
            command_slug = (
                f"{family['slug_prefix']}-{skill_dir.name}"
                if family["slug_prefix"]
                else skill_dir.name
            )
            spec = build_skill_spec(
                skill_dir,
                family["skill_prefix"],
                command_slug,
                source_label=f"Arcana/{family['name']}",
                source_kind="arcana",
                source_key=family["name"],
                source_repo="arcana",
            )
            if spec:
                specs.append(spec)
    return specs


def collect_one_grimoire_skill_specs(grimoire_root: Path, label: str) -> list[SkillSpec]:
    """Collect skills from one grimoire root."""
    if not grimoire_root.is_dir():
        info(f"{label}: directory not found at {grimoire_root} (skipping)")
        return []

    skills_dir = grimoire_root / "skills"
    if not skills_dir.is_dir():
        info(f"{label}: no skills/ directory (skipping)")
        return []

    metadata, skill_prefix = load_grimoire_metadata(grimoire_root, label)
    if not skill_prefix:
        return []

    source_label = metadata.get("name") or label
    specs: list[SkillSpec] = []
    for skill_dir in sorted(skills_dir.iterdir()):
        if not skill_dir.is_dir():
            continue
        if not is_valid_skill_slug(skill_dir.name):
            warn(f"{skill_dir}: invalid skill directory slug (skipping)")
            continue
        spec = build_skill_spec(
            skill_dir,
            skill_prefix,
            skill_dir.name,
            source_label=source_label,
            source_kind="grimoire",
            source_key=label,
            source_repo=source_label,
            grimoire_path=str(grimoire_root),
        )
        if spec:
            specs.append(spec)
    return specs


def collect_grimoire_skill_specs(grimoire_path: str | None = None) -> list[SkillSpec]:
    """Collect grimoire skills from the active grimoire or the local library."""
    if grimoire_path:
        local_path = resolve_grimoire_path(grimoire_path)
        return collect_one_grimoire_skill_specs(local_path, local_path.name)

    if not LOCAL_LIBRARY.is_file():
        info(f"No local library at {LOCAL_LIBRARY} - skipping grimoire skills")
        return []

    library = load_library(LOCAL_LIBRARY)
    specs: list[SkillSpec] = []
    for key in sorted(library.get("grimoires", {}).keys()):
        entry = library["grimoires"][key]
        local_path = resolve_grimoire_path(entry.get("local_path", ""))
        specs.extend(collect_one_grimoire_skill_specs(local_path, key))
    return specs


def collect_desired_skill_specs(grimoire_path: str | None = None) -> list[SkillSpec]:
    """Collect the complete desired registration set for one invocation."""
    return collect_arcana_skill_specs() + collect_grimoire_skill_specs(grimoire_path)


def ownership_payload(spec: SkillSpec) -> dict[str, Any]:
    """Return the ownership metadata embedded in generated SKILL.md files."""
    return {
        "schema_version": OWNERSHIP_SCHEMA_VERSION,
        "generation": REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": f"/{spec.command_name}",
        "source_kind": spec.source_kind,
        "source_key": spec.source_key,
        "source_label": spec.source_label,
        "source_repo": spec.source_repo,
        "source_path": str((spec.source_dir / "SKILL.md").resolve()),
        "grimoire_path": spec.grimoire_path,
    }


def ownership_comment(payload: dict[str, Any]) -> str:
    """Render a single-line ownership comment for SKILL.md."""
    return f"<!-- {OWNERSHIP_MARKER} {json.dumps(payload, sort_keys=True)} -->"


def normalized_path_text(path_text: str | Path) -> str:
    """Normalize a path string for generated-provenance comparisons.

    Collapses `.` / `..` segments via normpath so a crafted provenance path like
    `.../skills/../evil/SKILL.md` cannot slip past the under-known-root prefix
    check. Paths are normalized to POSIX separators on every platform.
    """
    text = str(path_text).strip().replace("\\", "/")
    text = os.path.normpath(text).replace("\\", "/")
    return text.rstrip("/").casefold()


def source_path_matches_spec(source_path: str, spec: SkillSpec) -> bool:
    """Return True when a generated provenance path points to a source skill."""
    expected = (spec.source_dir / "SKILL.md").resolve()
    return normalized_path_text(source_path) == normalized_path_text(expected)


def known_generated_source_roots(specs: list[SkillSpec]) -> set[Path]:
    """Return local source roots that can own generated skill pointers."""
    roots = {ARCANA_PATH / "skills"}
    for spec in specs:
        if spec.grimoire_path:
            roots.add(Path(spec.grimoire_path) / "skills")
    return roots


def source_path_is_under_known_root(source_path: str, specs: list[SkillSpec]) -> bool:
    """Return True when provenance points under a current generated-skill root."""
    source = normalized_path_text(source_path)
    for root in known_generated_source_roots(specs):
        root_text = normalized_path_text(root.resolve())
        if source.startswith(root_text + "/"):
            return True
    return False


def generated_provenance_owner(
    skill_dir: Path,
    content: str,
    desired_spec: SkillSpec | None,
    known_specs: list[SkillSpec],
) -> dict[str, Any] | None:
    """Return ownership inferred from Arcana's generated provenance comment."""
    match = GENERATED_SOURCE_RE.search(content)
    if not match:
        return None

    source_path = match.group(1).strip()
    if desired_spec:
        if not source_path_matches_spec(source_path, desired_spec):
            return None
        payload = ownership_payload(desired_spec)
    else:
        if not source_path_is_under_known_root(source_path, known_specs):
            return None
        payload = {
            "schema_version": OWNERSHIP_SCHEMA_VERSION,
            "generation": REGISTER_GENERATION,
            "registered_by": "arcana",
            "command": f"/{skill_dir.name}",
            "source_kind": "generated",
            "source_key": "",
            "source_label": "Generated skill",
            "source_repo": "",
            "source_path": source_path,
            "grimoire_path": "",
        }

    payload["ownership_basis"] = "generated_provenance"
    return payload


def insert_ownership_comment(content: str, spec: SkillSpec) -> str:
    """Insert generated ownership metadata after frontmatter."""
    payload = ownership_payload(spec)
    marker = ownership_comment(payload)
    provenance = (
        f"<!-- GENERATED - source: {spec.source_dir}/SKILL.md | "
        "DO NOT EDIT this file. Edit the source and run /arc-sync-skills. -->"
    )

    if content.startswith("---\n"):
        end = content.find("\n---", 4)
        if end != -1:
            insert_at = end + len("\n---")
            return content[:insert_at] + f"\n{marker}\n{provenance}\n" + content[insert_at:]
    return f"{marker}\n{provenance}\n{content}"


def _decode_ownership_payload(content: str, start: int) -> dict[str, Any] | None:
    """Decode the JSON object of an ownership marker at/after `start`.

    Uses a JSON decoder rather than a brace regex so a payload value containing
    '}' or '-->' does not truncate the parse and misclassify an owned skill.
    """
    brace = content.find("{", start)
    if brace == -1:
        return None
    try:
        payload, _ = json.JSONDecoder().raw_decode(content, brace)
    except json.JSONDecodeError:
        return None
    return payload if isinstance(payload, dict) else None


def read_skill_ownership(
    skill_dir: Path,
    desired_spec: SkillSpec | None = None,
    known_specs: list[SkillSpec] | None = None,
) -> dict[str, Any] | None:
    """Return Arcana ownership metadata from an installed skill directory."""
    skill_file = skill_dir / "SKILL.md"
    if not skill_file.is_file():
        return None
    try:
        content = skill_file.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    marker = OWNERSHIP_MARKER_RE.search(content)
    if not marker:
        return generated_provenance_owner(skill_dir, content, desired_spec, known_specs or [])
    payload = _decode_ownership_payload(content, marker.end())
    if payload is None:
        return None
    if payload.get("schema_version") != OWNERSHIP_SCHEMA_VERSION:
        return None
    if payload.get("registered_by") != "arcana":
        return None
    if not isinstance(payload.get("command"), str):
        return None
    return payload


def render_skill_files(spec: SkillSpec, pointer_only: bool) -> dict[str, str]:
    """Render files for one installed skill."""
    rendered: dict[str, str] = {}
    for source in sorted(spec.source_dir.iterdir()):
        if not source.is_file():
            continue
        if pointer_only and source.name != "SKILL.md":
            continue
        content = source.read_text(encoding="utf-8")
        content = content.replace(SKILL_PREFIX_PLACEHOLDER, spec.skill_prefix)
        content = content.replace("{{ARCANA_PATH}}", str(ARCANA_PATH))
        if spec.grimoire_path:
            content = content.replace("{{GRIMOIRE_PATH}}", spec.grimoire_path)
        if source.name == "SKILL.md":
            content = insert_ownership_comment(content, spec)
        rendered[source.name] = content
    return rendered


def detect_prefix_collisions(specs: list[SkillSpec]) -> list[PlanAction]:
    """Return blocking actions for source-level prefix collisions."""
    actions: list[PlanAction] = []
    arcana_prefixes = {
        spec.skill_prefix
        for spec in specs
        if spec.source_kind == "arcana"
    }
    grimoire_sources: dict[tuple[str, str], SkillSpec] = {}
    for spec in specs:
        if spec.source_kind != "grimoire":
            continue
        key = (spec.skill_prefix, spec.source_key)
        grimoire_sources.setdefault(key, spec)

    by_prefix: dict[str, list[SkillSpec]] = {}
    for (prefix, _source_key), spec in grimoire_sources.items():
        by_prefix.setdefault(prefix, []).append(spec)

    for prefix, prefix_specs in sorted(by_prefix.items()):
        if prefix in arcana_prefixes:
            labels = ", ".join(sorted({spec.source_label for spec in prefix_specs}))
            actions.append(PlanAction(
                action="collision",
                command_name=f"{prefix}-*",
                target_dir=Path(),
                reason=f"grimoire prefix {prefix!r} conflicts with Arcana command families ({labels})",
            ))
        if len(prefix_specs) > 1:
            labels = ", ".join(sorted({spec.source_label for spec in prefix_specs}))
            actions.append(PlanAction(
                action="collision",
                command_name=f"{prefix}-*",
                target_dir=Path(),
                reason=f"grimoire prefix {prefix!r} is used by multiple grimoires: {labels}",
            ))
    return actions


def detect_command_collisions(specs: list[SkillSpec]) -> list[PlanAction]:
    """Return blocking actions for duplicate desired command names."""
    by_command: dict[str, list[SkillSpec]] = {}
    for spec in specs:
        by_command.setdefault(spec.command_name, []).append(spec)

    actions: list[PlanAction] = []
    for command_name, command_specs in sorted(by_command.items()):
        if len(command_specs) <= 1:
            continue
        labels = ", ".join(
            f"{spec.source_label} ({spec.source_dir})"
            for spec in command_specs
        )
        actions.append(PlanAction(
            action="collision",
            command_name=command_name,
            target_dir=Path(),
            reason=f"multiple sources want /{command_name}: {labels}",
        ))
    return actions


def build_registration_plan(
    skills_target: Path,
    specs: list[SkillSpec],
    reset_managed: bool = False,
) -> dict[str, Any]:
    """Build a complete create/update/cleanup/collision plan."""
    blocking = detect_prefix_collisions(specs) + detect_command_collisions(specs)
    if blocking:
        return {"actions": [], "blocked": blocking}

    desired = {spec.command_name: spec for spec in specs}
    prefixes = tuple(f"{prefix}-" for prefix in sorted({spec.skill_prefix for spec in specs}))
    actions: list[PlanAction] = []

    if skills_target.is_dir() and prefixes:
        for skill_dir in sorted(skills_target.iterdir()):
            if not skill_dir.is_dir():
                continue
            if not skill_dir.name.startswith(prefixes):
                continue
            if reset_managed:
                continue
            if skill_dir.name in desired:
                continue
            owner = read_skill_ownership(skill_dir, known_specs=specs)
            if owner:
                actions.append(PlanAction(
                    action="cleanup",
                    command_name=skill_dir.name,
                    target_dir=skill_dir,
                    reason="owned stale generated skill",
                    owner=owner,
                ))
            else:
                actions.append(PlanAction(
                    action="preserve",
                    command_name=skill_dir.name,
                    target_dir=skill_dir,
                    reason="no Arcana ownership marker",
                ))

    for command_name, spec in sorted(desired.items()):
        target_dir = skills_target / command_name
        if target_dir.exists() and not target_dir.is_dir():
            blocking.append(PlanAction(
                action="collision",
                command_name=command_name,
                target_dir=target_dir,
                spec=spec,
                reason="target path exists but is not a directory",
            ))
            continue
        if target_dir.is_dir():
            if reset_managed:
                actions.append(PlanAction(
                    action="create",
                    command_name=command_name,
                    target_dir=target_dir,
                    spec=spec,
                ))
                continue
            owner = read_skill_ownership(target_dir, desired_spec=spec, known_specs=specs)
            if not owner:
                blocking.append(PlanAction(
                    action="collision",
                    command_name=command_name,
                    target_dir=target_dir,
                    spec=spec,
                    reason="target directory exists without Arcana ownership marker",
                ))
                continue
            if owner.get("command") != f"/{command_name}":
                blocking.append(PlanAction(
                    action="collision",
                    command_name=command_name,
                    target_dir=target_dir,
                    spec=spec,
                    reason=f"target is owned by {owner.get('command')}, not /{command_name}",
                    owner=owner,
                ))
                continue
            actions.append(PlanAction(
                action="update",
                command_name=command_name,
                target_dir=target_dir,
                spec=spec,
                owner=owner,
            ))
        else:
            actions.append(PlanAction(
                action="create",
                command_name=command_name,
                target_dir=target_dir,
                spec=spec,
            ))

    return {"actions": actions, "blocked": blocking}


def reset_managed_skill_dirs(
    skills_target: Path,
    specs: list[SkillSpec],
    dry_run: bool,
) -> int:
    """Remove owned skill dirs in the desired managed namespaces before registering.

    Only directories whose Arcana ownership can be proven - via the ownership
    marker or generated-source provenance - are removed. A directory that shares
    a managed prefix but carries no Arcana ownership is preserved; it surfaces as
    a collision in the registration plan instead of being deleted.
    """
    prefixes = tuple(f"{prefix}-" for prefix in sorted({spec.skill_prefix for spec in specs}))
    if not skills_target.is_dir() or not prefixes:
        return 0

    reset_count = 0
    for skill_dir in sorted(skills_target.iterdir()):
        if not skill_dir.is_dir() or not skill_dir.name.startswith(prefixes):
            continue
        owner = read_skill_ownership(skill_dir, known_specs=specs)
        if not owner:
            info(f"Preserve unowned: /{skill_dir.name} (no Arcana ownership marker)")
            continue
        verb = "Would reset managed namespace" if dry_run else "Reset managed namespace"
        info(f"{verb}: /{skill_dir.name}")
        if dry_run:
            reset_count += 1
        elif remove_owned_skill_dir(skill_dir, skills_target, owner=owner):
            reset_count += 1
    return reset_count


def print_plan(plan: dict[str, Any], dry_run: bool) -> None:
    """Print the registration plan in stable, greppable language."""
    for action in plan["blocked"]:
        target = f" at {action.target_dir}" if str(action.target_dir) not in {"", "."} else ""
        warn(f"Collision: /{action.command_name}{target} - {action.reason}")

    for action in plan["actions"]:
        if action.action == "preserve":
            info(f"Preserve unowned: /{action.command_name} ({action.reason})")
        elif action.action == "cleanup":
            verb = "Would clean owned stale" if dry_run else "Clean owned stale"
            info(f"{verb}: /{action.command_name}")
        elif action.action in {"create", "update"}:
            verb = (
                f"Would {action.action}"
                if dry_run
                else f"Plan {action.action}"
            )
            label = action.spec.source_label if action.spec else "unknown"
            info(f"{verb}: /{action.command_name} ({label})")


def remove_owned_skill_dir(
    skill_dir: Path,
    skills_target: Path,
    owner: dict[str, Any] | None = None,
) -> bool:
    """Remove an owned generated skill directory after scoped safety checks."""
    if not owner and not read_skill_ownership(skill_dir):
        warn(f"Refusing to remove unowned skill directory: {skill_dir}")
        return False
    try:
        if skill_dir.resolve().parent != skills_target.resolve():
            warn(f"Refusing to remove out-of-scope skill directory: {skill_dir}")
            return False
    except OSError as exc:
        warn(f"Could not resolve {skill_dir}: {exc}")
        return False
    shutil.rmtree(skill_dir)
    return True


def write_rendered_skill(
    spec: SkillSpec,
    target_dir: Path,
    skills_target: Path,
    pointer_only: bool,
    owner: dict[str, Any] | None = None,
) -> bool:
    """Write one rendered generated skill directory atomically.

    The full file set is rendered into a staging directory first, then swapped
    into place with os.replace, so an interrupt cannot leave a half-written or
    destroyed skill directory.
    """
    if (
        target_dir.exists()
        and not owner
        and not read_skill_ownership(target_dir, desired_spec=spec)
    ):
        warn(f"Refusing to overwrite unowned skill directory: {target_dir}")
        return False

    staging = target_dir.with_name(target_dir.name + ".tmp")
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents=True, exist_ok=True)
    for filename, content in render_skill_files(spec, pointer_only).items():
        with open(staging / filename, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)

    if target_dir.exists():
        if not remove_owned_skill_dir(target_dir, skills_target, owner=owner):
            shutil.rmtree(staging, ignore_errors=True)
            return False

    os.replace(staging, target_dir)
    ok(f"Registered: /{spec.command_name} ({spec.source_label})")
    return True


def apply_registration_plan(
    plan: dict[str, Any],
    skills_target: Path,
    pointer_only: bool,
    reporter: ResultReporter | None = None,
    label: str = "",
) -> tuple[int, int]:
    """Apply a collision-free registration plan. Returns (registered, cleaned).

    When a reporter is supplied, each successful clean/register is recorded as a
    mutation so the JSON envelope reflects exactly what was written.
    """
    if plan["blocked"]:
        return 0, 0

    skills_target.mkdir(parents=True, exist_ok=True)

    cleaned = 0
    registered = 0
    for action in plan["actions"]:
        if action.action == "cleanup":
            if remove_owned_skill_dir(action.target_dir, skills_target, owner=action.owner):
                cleaned += 1
                if reporter is not None:
                    reporter.mutation("remove", path=action.target_dir, detail=f"/{action.command_name} ({label})")

    for action in plan["actions"]:
        if action.action not in {"create", "update"} or action.spec is None:
            continue
        if write_rendered_skill(
            action.spec,
            action.target_dir,
            skills_target,
            pointer_only,
            owner=action.owner,
        ):
            registered += 1
            if reporter is not None:
                reporter.mutation("register", path=action.target_dir, detail=f"/{action.command_name} ({label})")

    return registered, cleaned


def selected_targets(agent: str):
    """Return target configurations for the requested agent."""
    if agent == "all":
        return SKILL_TARGETS.items()
    return [(agent, SKILL_TARGETS[agent])]


def register_target(
    agent_name: str,
    config: dict[str, Any],
    dry_run: bool = False,
    grimoire_path: str | None = None,
    reset_managed: bool = False,
    reporter: ResultReporter | None = None,
):
    """Plan and optionally register all skills for one agent target."""
    label = config["label"]
    skills_target = config["path"]
    pointer_only = config["pointer_only"]

    print(f"  Target: {label} ({skills_target})")
    if pointer_only:
        info("Pointer-only registration - copying SKILL.md files only")

    specs = collect_desired_skill_specs(grimoire_path)
    blocking = detect_prefix_collisions(specs) + detect_command_collisions(specs)
    reset_count = 0
    if reset_managed and not blocking:
        reset_count = reset_managed_skill_dirs(skills_target, specs, dry_run)
    plan = (
        {"actions": [], "blocked": blocking}
        if blocking
        else build_registration_plan(skills_target, specs, reset_managed=dry_run and reset_managed)
    )
    print_plan(plan, dry_run)

    # Record collisions and preserved-unowned dirs as messages on every run; in
    # dry-run, also record the planned creates/updates/cleanups as messages
    # (plan mode writes nothing, so they are not mutations). Apply-mode mutations
    # are recorded inside apply_registration_plan.
    if reporter is not None:
        for action in plan["blocked"]:
            target = action.target_dir if str(action.target_dir) not in {"", "."} else None
            reporter.message("error", f"collision /{action.command_name} ({label}): {action.reason}", path=target)
        for action in plan["actions"]:
            if action.action == "preserve":
                reporter.message("warning", f"preserved unowned /{action.command_name} ({label}): {action.reason}", path=action.target_dir)
        if dry_run:
            for action in plan["actions"]:
                if action.action in {"create", "update", "cleanup"}:
                    reporter.message("info", f"would {action.action} /{action.command_name} ({label})", path=action.target_dir)

    planned_registered = sum(
        1 for action in plan["actions"] if action.action in {"create", "update"}
    )
    planned_cleaned = sum(1 for action in plan["actions"] if action.action == "cleanup")
    preserved = sum(1 for action in plan["actions"] if action.action == "preserve")
    blocked = len(plan["blocked"])

    applied_registered = 0
    applied_cleaned = 0
    if not dry_run and not blocked:
        applied_registered, applied_cleaned = apply_registration_plan(
            plan,
            skills_target,
            pointer_only,
            reporter=reporter,
            label=label,
        )

    registered = planned_registered if dry_run else applied_registered
    cleaned = planned_cleaned if dry_run else applied_cleaned
    action = "would register" if dry_run else "registered"
    cleanup_action = "would clean" if dry_run else "cleaned"

    print()
    print(f"  {label}: {action} {registered} skill(s)")
    if cleaned > 0:
        print(f"  {label}: {cleanup_action} {cleaned} owned stale skill(s)")
    if reset_count > 0:
        reset_action = "would reset" if dry_run else "reset"
        print(f"  {label}: {reset_action} {reset_count} managed namespace skill dir(s)")
    if preserved > 0:
        print(f"  {label}: preserved {preserved} unowned skill dir(s)")
    if blocked > 0:
        print(f"  {label}: blocked by {blocked} collision(s)")
    print()

    return {
        "agent": agent_name,
        "label": label,
        "registered": registered,
        "cleaned": cleaned,
        "reset": reset_count,
        "preserved": preserved,
        "blocked": blocked,
        "mode": "plan" if dry_run else "apply",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Grimoire Skill Registration")
    parser.add_argument(
        "--agent",
        choices=["all", *sorted(SKILL_TARGETS)],
        default="all",
        help="Agent skill target from rites/data/agent_targets.json (default: all)",
    )
    parser.add_argument(
        "--grimoire",
        help=(
            "Only sync skills for this grimoire path after refreshing "
            "Arcana-shipped skills"
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without making changes",
    )
    parser.add_argument(
        "--reset-managed",
        action="store_true",
        help=(
            "Remove owned skill dirs in the managed Arcana/grimoire namespaces "
            "before registering; unowned dirs sharing a prefix are preserved. "
            "Use after major Arcana command-family changes."
        ),
    )
    add_output_format_arg(parser)
    args = parser.parse_args()
    human = args.format == "human"

    reporter = (
        None if human
        else ResultReporter("sync_skills", mode="plan" if args.dry_run else "apply")
    )

    # In json/jsonl mode the rite's human prose is suppressed so stdout carries
    # only the envelope; the structured outcome is captured into the reporter.
    sink = contextlib.nullcontext() if human else contextlib.redirect_stdout(io.StringIO())
    with sink:
        print()
        print("  Grimoire Skill Registration")
        print("  ----------------------------")
        print()

        if args.dry_run:
            info("Dry run mode - no files will be written")
            print()
        if args.grimoire:
            info(f"Grimoire scope: {resolve_grimoire_path(args.grimoire)}")
            print()
        if args.reset_managed:
            info("Reset managed mode - owned managed namespace skill dirs will be replaced")
            print()

        results = []
        for agent_name, config in selected_targets(args.agent):
            results.append(register_target(
                agent_name,
                config,
                args.dry_run,
                args.grimoire,
                args.reset_managed,
                reporter=reporter,
            ))

        print()
        print("  ----------------------------")
        total_registered = sum(result["registered"] for result in results)
        total_cleaned = sum(result["cleaned"] for result in results)
        total_reset = sum(result["reset"] for result in results)
        total_preserved = sum(result["preserved"] for result in results)
        total_blocked = sum(result["blocked"] for result in results)
        if args.dry_run:
            print(f"  Planned registrations: {total_registered} skill(s)")
            print(f"  Planned owned cleanups: {total_cleaned} stale skill(s)")
        else:
            print(f"  Registered: {total_registered} skill registration(s)")
            print(f"  Cleaned:    {total_cleaned} owned stale skill registration(s)")
        if total_preserved:
            print(f"  Preserved:  {total_preserved} unowned skill dir(s)")
        if total_reset:
            reset_label = "Planned reset" if args.dry_run else "Reset"
            print(f"  {reset_label}:      {total_reset} managed namespace skill dir(s)")
        if total_blocked:
            print(f"  Blocked:    {total_blocked} collision(s)")
        print()

        if not args.dry_run and total_registered > 0:
            labels = ", ".join(result["label"] for result in results)
            print(f"  Skills are now available for: {labels}.")
            print("  Try: /arc-help")
            print()

    if reporter is not None:
        reporter.emit(args.format, summary={
            "registered": total_registered,
            "cleaned": total_cleaned,
            "reset": total_reset,
            "preserved": total_preserved,
            "blocked": total_blocked,
        })

    if total_blocked and not args.dry_run:
        if human:
            print("  Resolve collisions before registration can write those targets.")
            print()
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
