"""Temp-target tests for the skill registration rite."""

import json
from pathlib import Path

import sync_skills as sync_skills


def _snapshot(root: Path) -> dict[str, str]:
    return {
        path.relative_to(root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _generated_comment(source_dir: Path) -> str:
    return (
        f"<!-- GENERATED - source: {source_dir}/SKILL.md | "
        "DO NOT EDIT this file. Edit the source and run /arc-sync skills. -->"
    )


def _legacy_generated_comment(source_dir: Path) -> str:
    # A generated-provenance comment in the em-dash separator form, carrying no
    # ARCANA_SKILL_OWNERSHIP marker.
    return (
        f"<!-- GENERATED — source: {source_dir}/SKILL.md | "
        "DO NOT EDIT this file. Edit the source and run /grm-skills-register. -->"
    )


def test_sync_skills_dry_run_plans_without_writing(tmp_path, monkeypatch, capsys):
    target = tmp_path / "codex" / "skills"
    # A managed-prefix dir not in the catalog is planned for cleanup, not preserved.
    existing = target / "arc-existing"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("stale, no marker\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = sync_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=True,
    )

    output = capsys.readouterr().out
    assert result["mode"] == "plan"
    assert result["registered"] > 0
    assert "Would create" in output
    assert "Would clean stale: /arc-existing" in output
    # Plan mode writes nothing.
    assert (existing / "SKILL.md").read_text(encoding="utf-8") == "stale, no marker\n"
    assert not (target / "arc-help").exists()


def test_sync_skills_apply_is_idempotent_for_pointer_target(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")
    config = {
        "label": "Codex Test",
        "path": target,
        "pointer_only": True,
    }

    first = sync_skills.register_target("codex", config, dry_run=False)
    first_snapshot = _snapshot(target)
    second = sync_skills.register_target("codex", config, dry_run=False)
    second_snapshot = _snapshot(target)

    assert first["mode"] == "apply"
    assert second["mode"] == "apply"
    assert first["registered"] == second["registered"]
    assert first_snapshot == second_snapshot
    assert (target / "arc-help" / "SKILL.md").is_file()
    assert "ARCANA_SKILL_OWNERSHIP" in (target / "arc-help" / "SKILL.md").read_text(encoding="utf-8")
    assert all(path.name == "SKILL.md" for path in target.rglob("*") if path.is_file())


def test_sync_skills_apply_leaves_no_staging_dir(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    sync_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
    )

    assert (target / "arc-help" / "SKILL.md").is_file()
    assert list(target.glob("*.tmp")) == []  # staging is swapped in, never left behind


def test_sync_skills_overwrites_unmarked_managed_dir(tmp_path, monkeypatch):
    # A directory under a managed prefix with no ownership marker is Arcana's to
    # replace - re-registering overwrites it with the current source, never blocks.
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("stale, no marker\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = sync_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
    )

    assert result["blocked"] == 0
    content = (existing / "SKILL.md").read_text(encoding="utf-8")
    assert "stale, no marker" not in content
    assert "ARCANA_SKILL_OWNERSHIP" in content


def test_sync_skills_reset_managed_replaces_unmarked_and_keeps_outside_namespace(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("stale, no marker\n", encoding="utf-8", newline="\n")
    outside_namespace = target / "personal-tool"  # NOT a managed prefix
    outside_namespace.mkdir()
    (outside_namespace / "SKILL.md").write_text("keep me\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = sync_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
        reset_managed=True,
    )

    # The unmarked managed-prefix dir is reset and re-registered; a directory
    # outside any managed prefix is never touched.
    assert result["reset"] >= 1
    assert result["blocked"] == 0
    assert "ARCANA_SKILL_OWNERSHIP" in (existing / "SKILL.md").read_text(encoding="utf-8")
    assert (outside_namespace / "SKILL.md").read_text(encoding="utf-8") == "keep me\n"


def test_reset_managed_skill_dirs_removes_all_managed(tmp_path):
    skills_target = tmp_path / "skills"

    unmarked = skills_target / "arc-mycustom"
    unmarked.mkdir(parents=True)
    (unmarked / "SKILL.md").write_text("hand-authored, no marker\n", encoding="utf-8", newline="\n")

    marked = skills_target / "arc-stale"
    marked.mkdir()
    marker = sync_skills.ownership_comment({
        "schema_version": sync_skills.OWNERSHIP_SCHEMA_VERSION,
        "generation": sync_skills.REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": "/arc-stale",
    })
    (marked / "SKILL.md").write_text(f"---\nname: arc-stale\n---\n{marker}\n", encoding="utf-8", newline="\n")

    outside = skills_target / "personal-tool"  # not a managed prefix
    outside.mkdir()
    (outside / "SKILL.md").write_text("keep me\n", encoding="utf-8", newline="\n")

    spec = sync_skills.SkillSpec(
        command_name="arc-help",
        command_slug="help",
        skill_prefix="arc",
        source_dir=tmp_path / "src",
        source_label="Arcana",
        source_kind="arcana",
        source_key="arcana",
        source_repo="arcana",
    )

    removed = sync_skills.reset_managed_skill_dirs(skills_target, [spec], dry_run=False)

    # Both managed-prefix dirs are removed regardless of ownership; the
    # outside-namespace dir is left alone.
    assert removed == 2
    assert not marked.exists()
    assert not unmarked.exists()
    assert outside.exists()


def test_sync_skills_reset_managed_dry_run_does_not_write(tmp_path, monkeypatch, capsys):
    target = tmp_path / "codex" / "skills"
    owned = target / "arc-help"
    owned.mkdir(parents=True)
    marker = sync_skills.ownership_comment({
        "schema_version": sync_skills.OWNERSHIP_SCHEMA_VERSION,
        "generation": sync_skills.REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": "/arc-help",
    })
    (owned / "SKILL.md").write_text(
        f"---\nname: arc-help\n---\n{marker}\nowned body\n", encoding="utf-8", newline="\n"
    )
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = sync_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=True,
        reset_managed=True,
    )

    output = capsys.readouterr().out
    assert result["mode"] == "plan"
    assert result["blocked"] == 0
    assert result["reset"] == 1
    assert "Would reset managed namespace: /arc-help" in output
    assert "Would create: /arc-help" in output
    assert (owned / "SKILL.md").read_text(encoding="utf-8").endswith("owned body\n")


def test_sync_skills_updates_generated_provenance_without_marker(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    source_dir = sync_skills.ARCANA_PATH / "skills" / "arc" / "help"
    (existing / "SKILL.md").write_text(
        "---\nname: arc-help\n---\n"
        f"{_generated_comment(source_dir)}\n"
        "old generated body\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = sync_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
    )

    content = (existing / "SKILL.md").read_text(encoding="utf-8")
    assert result["blocked"] == 0
    assert "ARCANA_SKILL_OWNERSHIP" in content
    assert "old generated body" not in content


def test_sync_skills_overwrites_legacy_marker_less_skill_for_update(tmp_path, monkeypatch):
    """A pre-marker generated skill (no ownership marker) under a managed prefix is
    overwritten in place by the current source, never blocked."""
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    source_dir = sync_skills.ARCANA_PATH / "skills" / "arc" / "help"
    (existing / "SKILL.md").write_text(
        "---\nname: arc-help\n---\n"
        f"{_legacy_generated_comment(source_dir)}\n"
        "old legacy body\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = sync_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
    )

    content = (existing / "SKILL.md").read_text(encoding="utf-8")
    assert result["blocked"] == 0
    assert "ARCANA_SKILL_OWNERSHIP" in content
    assert "old legacy body" not in content


def test_sync_skills_cleans_legacy_marker_less_orphan(tmp_path, monkeypatch):
    """A pre-marker generated skill no longer in the catalog (a rename or removal)
    is cleaned because it sits under a managed prefix, not left as an orphan."""
    target = tmp_path / "codex" / "skills"
    orphan = target / "arc-renamed-away"
    orphan.mkdir(parents=True)
    # Source path under Arcana's skills root but no longer present (the rename case).
    gone_source = sync_skills.ARCANA_PATH / "skills" / "arc" / "renamed-away"
    (orphan / "SKILL.md").write_text(
        "---\nname: arc-renamed-away\n---\n"
        f"{_legacy_generated_comment(gone_source)}\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = sync_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
    )

    assert result["cleaned"] >= 1
    assert not orphan.exists()


def test_sync_skills_cleans_all_stale_managed_entries(tmp_path, monkeypatch):
    # Every stale dir under a managed prefix is cleaned regardless of marker; a
    # directory outside any managed prefix is left alone.
    target = tmp_path / "codex" / "skills"
    marked_stale = target / "arc-old"
    marked_stale.mkdir(parents=True)
    marker = sync_skills.ownership_comment({
        "schema_version": sync_skills.OWNERSHIP_SCHEMA_VERSION,
        "generation": sync_skills.REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": "/arc-old",
    })
    (marked_stale / "SKILL.md").write_text(f"---\nname: arc-old\n---\n{marker}\n", encoding="utf-8", newline="\n")
    unmarked_stale = target / "arc-personal"
    unmarked_stale.mkdir()
    (unmarked_stale / "SKILL.md").write_text("no marker\n", encoding="utf-8", newline="\n")
    outside = target / "personal-tool"  # not a managed prefix
    outside.mkdir()
    (outside / "SKILL.md").write_text("keep me\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = sync_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
    )

    assert result["cleaned"] == 2
    assert not marked_stale.exists()
    assert not unmarked_stale.exists()
    assert (outside / "SKILL.md").is_file()


def test_register_target_reporter_records_apply_mutations(tmp_path, monkeypatch):
    """In apply mode the reporter records one mutation per registered skill, and
    stdout-facing prose is irrelevant to the structured envelope."""
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")
    reporter = sync_skills.ResultReporter("sync_skills", mode="apply")

    sync_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
        reporter=reporter,
    )

    report = reporter.report(summary={})
    assert report["rite"] == "sync_skills"
    assert report["status"] == "ok"
    assert any(m["action"] == "register" for m in report["mutations"])
    assert all(m["action"] in {"register", "remove"} for m in report["mutations"])


def test_register_target_reporter_dry_run_has_no_mutations(tmp_path, monkeypatch):
    """Plan mode records planned actions as messages, never mutations."""
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")
    reporter = sync_skills.ResultReporter("sync_skills", mode="plan")

    sync_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=True,
        reporter=reporter,
    )

    report = reporter.report(summary={})
    assert report["mutations"] == []
    assert report["status"] == "noop"
    assert any("would create" in m["message"] for m in report["messages"])


def test_sync_skills_blocks_grimoire_prefix_collisions(tmp_path, monkeypatch):
    home = tmp_path / "grimoires"
    first = home / "first-grimoire"
    second = home / "second-grimoire"
    for root, name in [(first, "First"), (second, "Second")]:
        skill = root / "skills" / "lookup"
        skill.mkdir(parents=True)
        (root / "grimoire.json").write_text(
            '{"name": "%s", "skill_prefix": "dup", "description": "test"}\n' % name,
            encoding="utf-8",
            newline="\n",
        )
        (skill / "SKILL.md").write_text(
            "---\nname: {{SKILL_PREFIX}}-lookup\ndescription: lookup\n---\n",
            encoding="utf-8",
            newline="\n",
        )
    library = home / "library.json"
    library.write_text(
        json.dumps({
            "grimoires": {
                "first-grimoire": {"local_path": str(first)},
                "second-grimoire": {"local_path": str(second)},
            }
        }) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(sync_skills, "LOCAL_LIBRARY", library)

    result = sync_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": tmp_path / "codex" / "skills",
            "pointer_only": True,
        },
        dry_run=True,
    )

    assert result["blocked"] >= 1
