"""Temp-target tests for the skill registration rite."""

import json
from pathlib import Path

import register_skills


def _snapshot(root: Path) -> dict[str, str]:
    return {
        path.relative_to(root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _generated_comment(source_dir: Path) -> str:
    return (
        f"<!-- GENERATED - source: {source_dir}/SKILL.md | "
        "DO NOT EDIT this file. Edit the source and run /arc-agent-register-skills. -->"
    )


def test_register_skills_dry_run_plans_without_writing(tmp_path, monkeypatch, capsys):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-existing"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=True,
    )

    output = capsys.readouterr().out
    assert result["mode"] == "plan"
    assert result["registered"] > 0
    assert "Would create" in output
    assert "Preserve unowned" in output
    assert (existing / "SKILL.md").read_text(encoding="utf-8") == "user-authored\n"
    assert not (target / "arc-help").exists()


def test_register_skills_apply_is_idempotent_for_pointer_target(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")
    config = {
        "label": "Codex Test",
        "path": target,
        "pointer_only": True,
    }

    first = register_skills.register_target("codex", config, dry_run=False)
    first_snapshot = _snapshot(target)
    second = register_skills.register_target("codex", config, dry_run=False)
    second_snapshot = _snapshot(target)

    assert first["mode"] == "apply"
    assert second["mode"] == "apply"
    assert first["registered"] == second["registered"]
    assert first_snapshot == second_snapshot
    assert (target / "arc-help" / "SKILL.md").is_file()
    assert "ARCANA_SKILL_OWNERSHIP" in (target / "arc-help" / "SKILL.md").read_text(encoding="utf-8")
    assert all(path.name == "SKILL.md" for path in target.rglob("*") if path.is_file())


def test_register_skills_preserves_unowned_collision(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
    )

    assert result["blocked"] == 1
    assert (existing / "SKILL.md").read_text(encoding="utf-8") == "user-authored\n"


def test_register_skills_reset_managed_replaces_unowned_collision(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    outside_namespace = target / "personal-tool"
    outside_namespace.mkdir()
    (outside_namespace / "SKILL.md").write_text("keep me\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
        reset_managed=True,
    )

    content = (existing / "SKILL.md").read_text(encoding="utf-8")
    assert result["blocked"] == 0
    assert result["reset"] == 1
    assert "ARCANA_SKILL_OWNERSHIP" in content
    assert "user-authored" not in content
    assert (outside_namespace / "SKILL.md").read_text(encoding="utf-8") == "keep me\n"


def test_register_skills_reset_managed_dry_run_does_not_write(tmp_path, monkeypatch, capsys):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=True,
        reset_managed=True,
    )

    output = capsys.readouterr().out
    assert result["mode"] == "plan"
    assert result["blocked"] == 0
    assert result["reset"] == 1
    assert "Would reset managed namespace: /arc-help" in output
    assert "Would create: /arc-help" in output
    assert (existing / "SKILL.md").read_text(encoding="utf-8") == "user-authored\n"


def test_register_skills_updates_generated_provenance_without_marker(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    source_dir = register_skills.ARCANA_PATH / "skills" / "help" / "help"
    (existing / "SKILL.md").write_text(
        "---\nname: arc-help\n---\n"
        f"{_generated_comment(source_dir)}\n"
        "old generated body\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
    )

    content = (existing / "SKILL.md").read_text(encoding="utf-8")
    assert result["blocked"] == 0
    assert "ARCANA_SKILL_OWNERSHIP" in content
    assert "old generated body" not in content


def test_register_skills_cleans_only_owned_stale_entries(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    owned_stale = target / "arc-old"
    owned_stale.mkdir(parents=True)
    marker = register_skills.ownership_comment({
        "schema_version": register_skills.OWNERSHIP_SCHEMA_VERSION,
        "generation": register_skills.REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": "/arc-old",
    })
    (owned_stale / "SKILL.md").write_text(f"---\nname: arc-old\n---\n{marker}\n", encoding="utf-8", newline="\n")
    unowned_stale = target / "arc-personal"
    unowned_stale.mkdir()
    (unowned_stale / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    generated_stale = target / "arc-retired"
    generated_stale.mkdir()
    retired_source = register_skills.ARCANA_PATH / "skills" / "arcana" / "retired"
    (generated_stale / "SKILL.md").write_text(
        "---\nname: arc-retired\n---\n"
        f"{_generated_comment(retired_source)}\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
    )

    assert result["cleaned"] == 2
    assert not owned_stale.exists()
    assert not generated_stale.exists()
    assert (unowned_stale / "SKILL.md").is_file()


def test_register_skills_blocks_grimoire_prefix_collisions(tmp_path, monkeypatch):
    home = tmp_path / "grimoires"
    first = home / "first-grimoire"
    second = home / "second-grimoire"
    for root, name in [(first, "First"), (second, "Second")]:
        skill = root / "skills" / "lookup"
        skill.mkdir(parents=True)
        (root / "grimoire.json").write_text(
            '{"name": "%s", "skill_prefix": "dup", "description": "test"}\n' % name,
            encoding="utf-8",
            newline="\n",
        )
        (skill / "SKILL.md").write_text(
            "---\nname: {{SKILL_PREFIX}}-lookup\ndescription: lookup\n---\n",
            encoding="utf-8",
            newline="\n",
        )
    library = home / "library.json"
    library.write_text(
        json.dumps({
            "grimoires": {
                "first-grimoire": {"local_path": str(first)},
                "second-grimoire": {"local_path": str(second)},
            }
        }) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", library)

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": tmp_path / "codex" / "skills",
            "pointer_only": True,
        },
        dry_run=True,
    )

    assert result["blocked"] >= 1
