"""Temp-target tests for the skill registration rite."""

import json
from pathlib import Path

import register_skills


def _snapshot(root: Path) -> dict[str, str]:
    return {
        path.relative_to(root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def _generated_comment(source_dir: Path) -> str:
    return (
        f"<!-- GENERATED - source: {source_dir}/SKILL.md | "
        "DO NOT EDIT this file. Edit the source and run /arc-agent-register-skills. -->"
    )


def _legacy_generated_comment(source_dir: Path) -> str:
    # The em-dash separator and /grm-skills-register reference that earlier rite
    # versions wrote, before the ARCANA_SKILL_OWNERSHIP marker existed.
    return (
        f"<!-- GENERATED — source: {source_dir}/SKILL.md | "
        "DO NOT EDIT this file. Edit the source and run /grm-skills-register. -->"
    )


def test_register_skills_dry_run_plans_without_writing(tmp_path, monkeypatch, capsys):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-existing"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=True,
    )

    output = capsys.readouterr().out
    assert result["mode"] == "plan"
    assert result["registered"] > 0
    assert "Would create" in output
    assert "Preserve unowned" in output
    assert (existing / "SKILL.md").read_text(encoding="utf-8") == "user-authored\n"
    assert not (target / "arc-help").exists()


def test_register_skills_apply_is_idempotent_for_pointer_target(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")
    config = {
        "label": "Codex Test",
        "path": target,
        "pointer_only": True,
    }

    first = register_skills.register_target("codex", config, dry_run=False)
    first_snapshot = _snapshot(target)
    second = register_skills.register_target("codex", config, dry_run=False)
    second_snapshot = _snapshot(target)

    assert first["mode"] == "apply"
    assert second["mode"] == "apply"
    assert first["registered"] == second["registered"]
    assert first_snapshot == second_snapshot
    assert (target / "arc-help" / "SKILL.md").is_file()
    assert "ARCANA_SKILL_OWNERSHIP" in (target / "arc-help" / "SKILL.md").read_text(encoding="utf-8")
    assert all(path.name == "SKILL.md" for path in target.rglob("*") if path.is_file())


def test_register_skills_apply_leaves_no_staging_dir(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    register_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
    )

    assert (target / "arc-help" / "SKILL.md").is_file()
    assert list(target.glob("*.tmp")) == []  # staging is swapped in, never left behind


def test_read_skill_ownership_handles_braces_in_payload(tmp_path):
    skill = tmp_path / "arc-weird"
    skill.mkdir()
    payload = {
        "schema_version": register_skills.OWNERSHIP_SCHEMA_VERSION,
        "generation": register_skills.REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": "/arc-weird",
        "source_label": "weird } --> label",
    }
    marker = register_skills.ownership_comment(payload)
    (skill / "SKILL.md").write_text(f"---\nname: arc-weird\n---\n{marker}\n", encoding="utf-8")

    owner = register_skills.read_skill_ownership(skill)

    # A '}' or '-->' inside a value must not truncate the parse into None.
    assert owner is not None
    assert owner["command"] == "/arc-weird"
    assert owner["source_label"] == "weird } --> label"


def test_register_skills_preserves_unowned_collision(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
    )

    assert result["blocked"] == 1
    assert (existing / "SKILL.md").read_text(encoding="utf-8") == "user-authored\n"


def test_register_skills_reset_managed_preserves_unowned_collision(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    (existing / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    outside_namespace = target / "personal-tool"
    outside_namespace.mkdir()
    (outside_namespace / "SKILL.md").write_text("keep me\n", encoding="utf-8", newline="\n")
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
        reset_managed=True,
    )

    # An unowned directory that shares a managed prefix is never reset/overwritten;
    # it surfaces as a collision and is left byte-identical.
    assert result["reset"] == 0
    assert result["blocked"] == 1
    assert (existing / "SKILL.md").read_text(encoding="utf-8") == "user-authored\n"
    assert (outside_namespace / "SKILL.md").read_text(encoding="utf-8") == "keep me\n"


def test_reset_managed_skill_dirs_removes_owned_preserves_unowned(tmp_path):
    skills_target = tmp_path / "skills"

    unowned = skills_target / "arc-mycustom"
    unowned.mkdir(parents=True)
    (unowned / "SKILL.md").write_text("hand-authored, no marker\n", encoding="utf-8", newline="\n")

    owned = skills_target / "arc-stale"
    owned.mkdir()
    marker = register_skills.ownership_comment({
        "schema_version": register_skills.OWNERSHIP_SCHEMA_VERSION,
        "generation": register_skills.REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": "/arc-stale",
    })
    (owned / "SKILL.md").write_text(f"---\nname: arc-stale\n---\n{marker}\n", encoding="utf-8", newline="\n")

    spec = register_skills.SkillSpec(
        command_name="arc-help",
        command_slug="help",
        skill_prefix="arc",
        source_dir=tmp_path / "src",
        source_label="Arcana",
        source_kind="arcana",
        source_key="arcana",
        source_repo="arcana",
    )

    removed = register_skills.reset_managed_skill_dirs(skills_target, [spec], dry_run=False)

    assert removed == 1
    assert not owned.exists()
    assert unowned.exists()
    assert (unowned / "SKILL.md").read_text(encoding="utf-8") == "hand-authored, no marker\n"


def test_register_skills_reset_managed_dry_run_does_not_write(tmp_path, monkeypatch, capsys):
    target = tmp_path / "codex" / "skills"
    owned = target / "arc-help"
    owned.mkdir(parents=True)
    marker = register_skills.ownership_comment({
        "schema_version": register_skills.OWNERSHIP_SCHEMA_VERSION,
        "generation": register_skills.REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": "/arc-help",
    })
    (owned / "SKILL.md").write_text(
        f"---\nname: arc-help\n---\n{marker}\nowned body\n", encoding="utf-8", newline="\n"
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=True,
        reset_managed=True,
    )

    output = capsys.readouterr().out
    assert result["mode"] == "plan"
    assert result["blocked"] == 0
    assert result["reset"] == 1
    assert "Would reset managed namespace: /arc-help" in output
    assert "Would create: /arc-help" in output
    assert (owned / "SKILL.md").read_text(encoding="utf-8").endswith("owned body\n")


def test_register_skills_updates_generated_provenance_without_marker(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    source_dir = register_skills.ARCANA_PATH / "skills" / "help" / "help"
    (existing / "SKILL.md").write_text(
        "---\nname: arc-help\n---\n"
        f"{_generated_comment(source_dir)}\n"
        "old generated body\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
    )

    content = (existing / "SKILL.md").read_text(encoding="utf-8")
    assert result["blocked"] == 0
    assert "ARCANA_SKILL_OWNERSHIP" in content
    assert "old generated body" not in content


def test_register_skills_recognizes_legacy_em_dash_provenance_for_update(tmp_path, monkeypatch):
    """A legacy em-dash generated skill (no ownership marker) is provably owned,
    so it is updated in place rather than blocked as an unowned collision."""
    target = tmp_path / "codex" / "skills"
    existing = target / "arc-help"
    existing.mkdir(parents=True)
    source_dir = register_skills.ARCANA_PATH / "skills" / "help" / "help"
    (existing / "SKILL.md").write_text(
        "---\nname: arc-help\n---\n"
        f"{_legacy_generated_comment(source_dir)}\n"
        "old legacy body\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
    )

    content = (existing / "SKILL.md").read_text(encoding="utf-8")
    assert result["blocked"] == 0
    assert "ARCANA_SKILL_OWNERSHIP" in content
    assert "old legacy body" not in content


def test_register_skills_cleans_legacy_em_dash_orphan(tmp_path, monkeypatch):
    """A legacy em-dash generated skill whose source no longer exists (a rename
    or removal) is recognized as owned and cleaned, not preserved as an orphan."""
    target = tmp_path / "codex" / "skills"
    orphan = target / "arc-renamed-away"
    orphan.mkdir(parents=True)
    # Source path under Arcana's skills root but no longer present (the rename case).
    gone_source = register_skills.ARCANA_PATH / "skills" / "arcana" / "renamed-away"
    (orphan / "SKILL.md").write_text(
        "---\nname: arc-renamed-away\n---\n"
        f"{_legacy_generated_comment(gone_source)}\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
    )

    assert result["cleaned"] >= 1
    assert not orphan.exists()


def test_register_skills_cleans_only_owned_stale_entries(tmp_path, monkeypatch):
    target = tmp_path / "codex" / "skills"
    owned_stale = target / "arc-old"
    owned_stale.mkdir(parents=True)
    marker = register_skills.ownership_comment({
        "schema_version": register_skills.OWNERSHIP_SCHEMA_VERSION,
        "generation": register_skills.REGISTER_GENERATION,
        "registered_by": "arcana",
        "command": "/arc-old",
    })
    (owned_stale / "SKILL.md").write_text(f"---\nname: arc-old\n---\n{marker}\n", encoding="utf-8", newline="\n")
    unowned_stale = target / "arc-personal"
    unowned_stale.mkdir()
    (unowned_stale / "SKILL.md").write_text("user-authored\n", encoding="utf-8", newline="\n")
    generated_stale = target / "arc-retired"
    generated_stale.mkdir()
    retired_source = register_skills.ARCANA_PATH / "skills" / "arcana" / "retired"
    (generated_stale / "SKILL.md").write_text(
        "---\nname: arc-retired\n---\n"
        f"{_generated_comment(retired_source)}\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": target,
            "pointer_only": True,
        },
        dry_run=False,
    )

    assert result["cleaned"] == 2
    assert not owned_stale.exists()
    assert not generated_stale.exists()
    assert (unowned_stale / "SKILL.md").is_file()


def test_register_target_reporter_records_apply_mutations(tmp_path, monkeypatch):
    """In apply mode the reporter records one mutation per registered skill, and
    stdout-facing prose is irrelevant to the structured envelope."""
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")
    reporter = register_skills.ResultReporter("register_skills", mode="apply")

    register_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=False,
        reporter=reporter,
    )

    report = reporter.report(summary={})
    assert report["rite"] == "register_skills"
    assert report["status"] == "ok"
    assert any(m["action"] == "register" for m in report["mutations"])
    assert all(m["action"] in {"register", "remove"} for m in report["mutations"])


def test_register_target_reporter_dry_run_has_no_mutations(tmp_path, monkeypatch):
    """Plan mode records planned actions as messages, never mutations."""
    target = tmp_path / "codex" / "skills"
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", tmp_path / "missing-library.json")
    reporter = register_skills.ResultReporter("register_skills", mode="plan")

    register_skills.register_target(
        "codex",
        {"label": "Codex Test", "path": target, "pointer_only": True},
        dry_run=True,
        reporter=reporter,
    )

    report = reporter.report(summary={})
    assert report["mutations"] == []
    assert report["status"] == "noop"
    assert any("would create" in m["message"] for m in report["messages"])


def test_source_path_under_root_rejects_dotdot_escape():
    """A provenance path that uses `..` to climb out of a known skills root must
    not be treated as under that root (it could otherwise be claimed as owned)."""
    root = register_skills.ARCANA_PATH / "skills"
    legit = str(root / "help" / "SKILL.md")
    escape = str(root / ".." / "evil" / "SKILL.md")
    assert register_skills.source_path_is_under_known_root(legit, [])
    assert not register_skills.source_path_is_under_known_root(escape, [])


def test_register_skills_blocks_grimoire_prefix_collisions(tmp_path, monkeypatch):
    home = tmp_path / "grimoires"
    first = home / "first-grimoire"
    second = home / "second-grimoire"
    for root, name in [(first, "First"), (second, "Second")]:
        skill = root / "skills" / "lookup"
        skill.mkdir(parents=True)
        (root / "grimoire.json").write_text(
            '{"name": "%s", "skill_prefix": "dup", "description": "test"}\n' % name,
            encoding="utf-8",
            newline="\n",
        )
        (skill / "SKILL.md").write_text(
            "---\nname: {{SKILL_PREFIX}}-lookup\ndescription: lookup\n---\n",
            encoding="utf-8",
            newline="\n",
        )
    library = home / "library.json"
    library.write_text(
        json.dumps({
            "grimoires": {
                "first-grimoire": {"local_path": str(first)},
                "second-grimoire": {"local_path": str(second)},
            }
        }) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    monkeypatch.setattr(register_skills, "LOCAL_LIBRARY", library)

    result = register_skills.register_target(
        "codex",
        {
            "label": "Codex Test",
            "path": tmp_path / "codex" / "skills",
            "pointer_only": True,
        },
        dry_run=True,
    )

    assert result["blocked"] >= 1
